on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: Compile the pinenote kernel
    steps:
      - name: Docker-based compilation
        id: compile-kernel-in-docker
        uses: m-weigand/ci_test_1@main
      - run: env
      - uses: actions/upload-artifact@v3
        with:
          name: mutter
          path: ${{ runner.temp }}/_github_home/mutter_arm64_debs
