on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test releases
    steps:
      - name: get pwd
        run: pwd
      - name: create dummy file
        run: touch release_binary_dummy
      - name: ls
        run: ls
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: dummy_file
          path: release_binary_dummy
  draft_release_job:
    # if: startsWith(github.ref, 'refs/tags/')
    # if: contains(github.ref, "main")
    runs-on: ubuntu-latest
    needs:
      - hello_world_job
    steps:
      - name: Clone workflow repository
        uses: actions/checkout@v3
      - name: Download image artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - name: Make release
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: true
          files: |
            artifacts/release_binary_dummy
